import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { Database } from '@/integrations/supabase/types';
import { useAuth } from '@/context/AuthContext';

type Order = Database['public']['Tables']['orders']['Row'];
type OrderItem = Database['public']['Tables']['order_items']['Row'];
type OrderStatus = Database['public']['Enums']['order_status'];

interface OrderWithDetails extends Order {
  stores?: Database['public']['Tables']['stores']['Row'] | null;
  order_items?: OrderItem[];
  rider?: Database['public']['Tables']['profiles']['Row'] | null;
}

export const useOrders = () => {
  const { profile } = useAuth();

  return useQuery({
    queryKey: ['orders', profile?.id],
    queryFn: async () => {
      if (!profile) return [];

      const { data, error } = await supabase
        .from('orders')
        .select(`
          *,
          stores(*),
          order_items(*),
          rider:profiles!orders_rider_id_fkey(*)
        `)
        .eq('customer_id', profile.id)
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data as OrderWithDetails[];
    },
    enabled: !!profile,
  });
};

export const useOrder = (orderId: string) => {
  return useQuery({
    queryKey: ['order', orderId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('orders')
        .select(`
          *,
          stores(*),
          order_items(*),
          rider:profiles!orders_rider_id_fkey(*),
          customer:profiles!orders_customer_id_fkey(*)
        `)
        .eq('id', orderId)
        .maybeSingle();

      if (error) throw error;
      if (!data) throw new Error('Order not found or access denied');
      return data as OrderWithDetails & { customer?: { full_name?: string; phone?: string } };
    },
    enabled: !!orderId,
    retry: (failureCount, error) => {
      // Don't retry if order not found / access denied
      if (error?.message?.includes('Order not found')) return false;
      return failureCount < 2;
    },
  });
};

export const useRiderOrders = () => {
  const { profile } = useAuth();

  return useQuery({
    queryKey: ['rider-orders', profile?.id],
    queryFn: async () => {
      if (!profile) return [];

      const { data, error } = await supabase
        .from('orders')
        .select(`
          *,
          stores(*),
          order_items(*),
          customer:profiles!orders_customer_id_fkey(*)
        `)
        .eq('rider_id', profile.id)
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data;
    },
    enabled: !!profile && profile.role === 'rider',
  });
};

export const useAvailableOrders = () => {
  return useQuery({
    queryKey: ['available-orders'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('orders')
        .select(`
          *,
          stores(*),
          order_items(*),
          customer:profiles!orders_customer_id_fkey(full_name, phone, address)
        `)
        .is('rider_id', null)
        .in('status', ['pending', 'confirmed', 'ready_for_pickup'])
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data;
    },
  });
};

export const useCreateOrder = () => {
  const queryClient = useQueryClient();
  const { profile } = useAuth();

  return useMutation({
    mutationFn: async (orderData: {
      store_id: string;
      items: { product_id: string; product_name: string; quantity: number; unit_price: number }[];
      delivery_address: string;
      delivery_lat?: number;
      delivery_lng?: number;
      pickup_address?: string;
      pickup_lat?: number;
      pickup_lng?: number;
      notes?: string;
      delivery_fee: number;
    }) => {
      if (!profile) throw new Error('Not authenticated');

      const subtotal = orderData.items.reduce(
        (sum, item) => sum + item.unit_price * item.quantity,
        0
      );
      const total = subtotal + orderData.delivery_fee;

      // Create order - order_number is auto-generated by trigger
      const { data: order, error: orderError } = await supabase
        .from('orders')
        .insert([{
          customer_id: profile.id,
          store_id: orderData.store_id,
          delivery_address: orderData.delivery_address,
          delivery_lat: orderData.delivery_lat,
          delivery_lng: orderData.delivery_lng,
          pickup_address: orderData.pickup_address,
          pickup_lat: orderData.pickup_lat,
          pickup_lng: orderData.pickup_lng,
          notes: orderData.notes,
          subtotal,
          delivery_fee: orderData.delivery_fee,
          total,
          estimated_delivery: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
        }])
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items
      const orderItems = orderData.items.map((item) => ({
        order_id: order.id,
        product_id: item.product_id,
        product_name: item.product_name,
        quantity: item.quantity,
        unit_price: item.unit_price,
        total_price: item.unit_price * item.quantity,
      }));

      const { error: itemsError } = await supabase.from('order_items').insert(orderItems);

      if (itemsError) throw itemsError;

      return order;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
    },
  });
};

export const useUpdateOrderStatus = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ orderId, status }: { orderId: string; status: OrderStatus }) => {
      const updates: Partial<Order> = { status };
      
      if (status === 'delivered') {
        updates.delivered_at = new Date().toISOString();
      }

      const { data, error } = await supabase
        .from('orders')
        .update(updates)
        .eq('id', orderId)
        .select()
        .single();

      if (error) {
        console.error('Update order status error:', error);
        throw new Error(`Failed to update order: ${error.message}`);
      }
      return data;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
      queryClient.invalidateQueries({ queryKey: ['order', variables.orderId] });
      queryClient.invalidateQueries({ queryKey: ['rider-orders'] });
      queryClient.invalidateQueries({ queryKey: ['available-orders'] });
      queryClient.invalidateQueries({ queryKey: ['rider-pending-orders'] });
      queryClient.invalidateQueries({ queryKey: ['rider-active-orders'] });
    },
  });
};

export const useAcceptOrder = () => {
  const queryClient = useQueryClient();
  const { profile } = useAuth();

  return useMutation({
    mutationFn: async (orderId: string) => {
      if (!profile) throw new Error('Not authenticated');

      // First check if order is still available
      const { data: existingOrder, error: checkError } = await supabase
        .from('orders')
        .select('id, rider_id, status')
        .eq('id', orderId)
        .maybeSingle();

      if (checkError) throw checkError;
      if (!existingOrder) throw new Error('Order not found');
      if (existingOrder.rider_id) throw new Error('Order already accepted by another rider');

      // Atomically update only if rider_id is still null
      const { data, error } = await supabase
        .from('orders')
        .update({
          rider_id: profile.id,
          status: 'confirmed',
        })
        .eq('id', orderId)
        .is('rider_id', null)
        .select()
        .single();

      if (error) {
        if (error.code === 'PGRST116') {
          throw new Error('Order already accepted by another rider');
        }
        throw error;
      }
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
      queryClient.invalidateQueries({ queryKey: ['rider-orders'] });
      queryClient.invalidateQueries({ queryKey: ['available-orders'] });
      queryClient.invalidateQueries({ queryKey: ['rider-pending-orders'] });
      queryClient.invalidateQueries({ queryKey: ['rider-active-orders'] });
    },
  });
};
